version: '3'

services:
  code:
    build:
      context: './code'
    image: tesh/procon4-code
    container_name: procod
    volumes:
      - './code:/code'
    init: true
    command: ['sleep', 'infinity']
  judge:
    build:
      context: './judge'
    image: tesh/procon4-judge
    container_name: projdg
    init: true
    tty: true
    volumes:
      - './judge:/judge'
      - './code:/code'
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: ['./startup.sh']
  doc:
    build:
      context: './doc'
    image: tesh/procon4-doc
    container_name: prodoc
    volumes:
      - './doc:/doc'
      - './code:/code'
      - '/doc/node_modules'
    ports:
      - '4321:4321'
    command: ['yarn', 'dev']
